FROM golang:1.20

RUN go install golang.org/x/tools/gopls@latest
RUN go install github.com/rogpeppe/godef@latest
RUN go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
RUN go install github.com/mdempsky/gocode@latest
